// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/JihadRinaldi/go-shop/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUploadRepositoryInterface is an autogenerated mock type for the UploadRepositoryInterface type
type MockUploadRepositoryInterface struct {
	mock.Mock
}

type MockUploadRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadRepositoryInterface) EXPECT() *MockUploadRepositoryInterface_Expecter {
	return &MockUploadRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateProductImage provides a mock function with given fields: image
func (_m *MockUploadRepositoryInterface) CreateProductImage(image *models.ProductImage) error {
	ret := _m.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for CreateProductImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ProductImage) error); ok {
		r0 = rf(image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploadRepositoryInterface_CreateProductImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProductImage'
type MockUploadRepositoryInterface_CreateProductImage_Call struct {
	*mock.Call
}

// CreateProductImage is a helper method to define mock.On call
//   - image *models.ProductImage
func (_e *MockUploadRepositoryInterface_Expecter) CreateProductImage(image interface{}) *MockUploadRepositoryInterface_CreateProductImage_Call {
	return &MockUploadRepositoryInterface_CreateProductImage_Call{Call: _e.mock.On("CreateProductImage", image)}
}

func (_c *MockUploadRepositoryInterface_CreateProductImage_Call) Run(run func(image *models.ProductImage)) *MockUploadRepositoryInterface_CreateProductImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ProductImage))
	})
	return _c
}

func (_c *MockUploadRepositoryInterface_CreateProductImage_Call) Return(_a0 error) *MockUploadRepositoryInterface_CreateProductImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUploadRepositoryInterface_CreateProductImage_Call) RunAndReturn(run func(*models.ProductImage) error) *MockUploadRepositoryInterface_CreateProductImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProductImage provides a mock function with given fields: id
func (_m *MockUploadRepositoryInterface) DeleteProductImage(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploadRepositoryInterface_DeleteProductImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProductImage'
type MockUploadRepositoryInterface_DeleteProductImage_Call struct {
	*mock.Call
}

// DeleteProductImage is a helper method to define mock.On call
//   - id uint
func (_e *MockUploadRepositoryInterface_Expecter) DeleteProductImage(id interface{}) *MockUploadRepositoryInterface_DeleteProductImage_Call {
	return &MockUploadRepositoryInterface_DeleteProductImage_Call{Call: _e.mock.On("DeleteProductImage", id)}
}

func (_c *MockUploadRepositoryInterface_DeleteProductImage_Call) Run(run func(id uint)) *MockUploadRepositoryInterface_DeleteProductImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUploadRepositoryInterface_DeleteProductImage_Call) Return(_a0 error) *MockUploadRepositoryInterface_DeleteProductImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUploadRepositoryInterface_DeleteProductImage_Call) RunAndReturn(run func(uint) error) *MockUploadRepositoryInterface_DeleteProductImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductImages provides a mock function with given fields: productID
func (_m *MockUploadRepositoryInterface) GetProductImages(productID uint) ([]models.ProductImage, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductImages")
	}

	var r0 []models.ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.ProductImage, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.ProductImage); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUploadRepositoryInterface_GetProductImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductImages'
type MockUploadRepositoryInterface_GetProductImages_Call struct {
	*mock.Call
}

// GetProductImages is a helper method to define mock.On call
//   - productID uint
func (_e *MockUploadRepositoryInterface_Expecter) GetProductImages(productID interface{}) *MockUploadRepositoryInterface_GetProductImages_Call {
	return &MockUploadRepositoryInterface_GetProductImages_Call{Call: _e.mock.On("GetProductImages", productID)}
}

func (_c *MockUploadRepositoryInterface_GetProductImages_Call) Run(run func(productID uint)) *MockUploadRepositoryInterface_GetProductImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUploadRepositoryInterface_GetProductImages_Call) Return(_a0 []models.ProductImage, _a1 error) *MockUploadRepositoryInterface_GetProductImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUploadRepositoryInterface_GetProductImages_Call) RunAndReturn(run func(uint) ([]models.ProductImage, error)) *MockUploadRepositoryInterface_GetProductImages_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrimaryImage provides a mock function with given fields: productID, imageID
func (_m *MockUploadRepositoryInterface) SetPrimaryImage(productID uint, imageID uint) error {
	ret := _m.Called(productID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for SetPrimaryImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(productID, imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploadRepositoryInterface_SetPrimaryImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrimaryImage'
type MockUploadRepositoryInterface_SetPrimaryImage_Call struct {
	*mock.Call
}

// SetPrimaryImage is a helper method to define mock.On call
//   - productID uint
//   - imageID uint
func (_e *MockUploadRepositoryInterface_Expecter) SetPrimaryImage(productID interface{}, imageID interface{}) *MockUploadRepositoryInterface_SetPrimaryImage_Call {
	return &MockUploadRepositoryInterface_SetPrimaryImage_Call{Call: _e.mock.On("SetPrimaryImage", productID, imageID)}
}

func (_c *MockUploadRepositoryInterface_SetPrimaryImage_Call) Run(run func(productID uint, imageID uint)) *MockUploadRepositoryInterface_SetPrimaryImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockUploadRepositoryInterface_SetPrimaryImage_Call) Return(_a0 error) *MockUploadRepositoryInterface_SetPrimaryImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUploadRepositoryInterface_SetPrimaryImage_Call) RunAndReturn(run func(uint, uint) error) *MockUploadRepositoryInterface_SetPrimaryImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUploadRepositoryInterface creates a new instance of MockUploadRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadRepositoryInterface {
	mock := &MockUploadRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
