// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/JihadRinaldi/go-shop/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: user
func (_m *MockUserRepositoryInterface) Create(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepositoryInterface_Expecter) Create(user interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(user *models.User)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(_a0 error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(*models.User) error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefreshToken provides a mock function with given fields: token
func (_m *MockUserRepositoryInterface) CreateRefreshToken(token *models.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockUserRepositoryInterface_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - token *models.RefreshToken
func (_e *MockUserRepositoryInterface_Expecter) CreateRefreshToken(token interface{}) *MockUserRepositoryInterface_CreateRefreshToken_Call {
	return &MockUserRepositoryInterface_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", token)}
}

func (_c *MockUserRepositoryInterface_CreateRefreshToken_Call) Run(run func(token *models.RefreshToken)) *MockUserRepositoryInterface_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.RefreshToken))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_CreateRefreshToken_Call) Return(_a0 error) *MockUserRepositoryInterface_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_CreateRefreshToken_Call) RunAndReturn(run func(*models.RefreshToken) error) *MockUserRepositoryInterface_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockUserRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockUserRepositoryInterface_Expecter) Delete(id interface{}) *MockUserRepositoryInterface_Delete_Call {
	return &MockUserRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserRepositoryInterface_Delete_Call) Run(run func(id uint)) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) Return(_a0 error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) RunAndReturn(run func(uint) error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function with given fields: token
func (_m *MockUserRepositoryInterface) DeleteRefreshToken(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockUserRepositoryInterface_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockUserRepositoryInterface_Expecter) DeleteRefreshToken(token interface{}) *MockUserRepositoryInterface_DeleteRefreshToken_Call {
	return &MockUserRepositoryInterface_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", token)}
}

func (_c *MockUserRepositoryInterface_DeleteRefreshToken_Call) Run(run func(token string)) *MockUserRepositoryInterface_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_DeleteRefreshToken_Call) Return(_a0 error) *MockUserRepositoryInterface_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_DeleteRefreshToken_Call) RunAndReturn(run func(string) error) *MockUserRepositoryInterface_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshTokenByID provides a mock function with given fields: id
func (_m *MockUserRepositoryInterface) DeleteRefreshTokenByID(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshTokenByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_DeleteRefreshTokenByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshTokenByID'
type MockUserRepositoryInterface_DeleteRefreshTokenByID_Call struct {
	*mock.Call
}

// DeleteRefreshTokenByID is a helper method to define mock.On call
//   - id uint
func (_e *MockUserRepositoryInterface_Expecter) DeleteRefreshTokenByID(id interface{}) *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call {
	return &MockUserRepositoryInterface_DeleteRefreshTokenByID_Call{Call: _e.mock.On("DeleteRefreshTokenByID", id)}
}

func (_c *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call) Run(run func(id uint)) *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call) Return(_a0 error) *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call) RunAndReturn(run func(uint) error) *MockUserRepositoryInterface_DeleteRefreshTokenByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: email
func (_m *MockUserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepositoryInterface_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepositoryInterface_Expecter) GetByEmail(email interface{}) *MockUserRepositoryInterface_GetByEmail_Call {
	return &MockUserRepositoryInterface_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockUserRepositoryInterface_GetByEmail_Call) Run(run func(email string)) *MockUserRepositoryInterface_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetByEmail_Call) RunAndReturn(run func(string) (*models.User, error)) *MockUserRepositoryInterface_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmailAndActive provides a mock function with given fields: email, isActive
func (_m *MockUserRepositoryInterface) GetByEmailAndActive(email string, isActive bool) (*models.User, error) {
	ret := _m.Called(email, isActive)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmailAndActive")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*models.User, error)); ok {
		return rf(email, isActive)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *models.User); ok {
		r0 = rf(email, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(email, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetByEmailAndActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmailAndActive'
type MockUserRepositoryInterface_GetByEmailAndActive_Call struct {
	*mock.Call
}

// GetByEmailAndActive is a helper method to define mock.On call
//   - email string
//   - isActive bool
func (_e *MockUserRepositoryInterface_Expecter) GetByEmailAndActive(email interface{}, isActive interface{}) *MockUserRepositoryInterface_GetByEmailAndActive_Call {
	return &MockUserRepositoryInterface_GetByEmailAndActive_Call{Call: _e.mock.On("GetByEmailAndActive", email, isActive)}
}

func (_c *MockUserRepositoryInterface_GetByEmailAndActive_Call) Run(run func(email string, isActive bool)) *MockUserRepositoryInterface_GetByEmailAndActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetByEmailAndActive_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_GetByEmailAndActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetByEmailAndActive_Call) RunAndReturn(run func(string, bool) (*models.User, error)) *MockUserRepositoryInterface_GetByEmailAndActive_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockUserRepositoryInterface) GetByID(id uint) (*models.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockUserRepositoryInterface_Expecter) GetByID(id interface{}) *MockUserRepositoryInterface_GetByID_Call {
	return &MockUserRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockUserRepositoryInterface_GetByID_Call) Run(run func(id uint)) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetByID_Call) RunAndReturn(run func(uint) (*models.User, error)) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidRefreshToken provides a mock function with given fields: token
func (_m *MockUserRepositoryInterface) GetValidRefreshToken(token string) (*models.RefreshToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetValidRefreshToken")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.RefreshToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.RefreshToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetValidRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidRefreshToken'
type MockUserRepositoryInterface_GetValidRefreshToken_Call struct {
	*mock.Call
}

// GetValidRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockUserRepositoryInterface_Expecter) GetValidRefreshToken(token interface{}) *MockUserRepositoryInterface_GetValidRefreshToken_Call {
	return &MockUserRepositoryInterface_GetValidRefreshToken_Call{Call: _e.mock.On("GetValidRefreshToken", token)}
}

func (_c *MockUserRepositoryInterface_GetValidRefreshToken_Call) Run(run func(token string)) *MockUserRepositoryInterface_GetValidRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetValidRefreshToken_Call) Return(_a0 *models.RefreshToken, _a1 error) *MockUserRepositoryInterface_GetValidRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetValidRefreshToken_Call) RunAndReturn(run func(string) (*models.RefreshToken, error)) *MockUserRepositoryInterface_GetValidRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: user
func (_m *MockUserRepositoryInterface) Update(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepositoryInterface_Expecter) Update(user interface{}) *MockUserRepositoryInterface_Update_Call {
	return &MockUserRepositoryInterface_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserRepositoryInterface_Update_Call) Run(run func(user *models.User)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) Return(_a0 error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) RunAndReturn(run func(*models.User) error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
