// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/JihadRinaldi/go-shop/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepositoryInterface is an autogenerated mock type for the OrderRepositoryInterface type
type MockOrderRepositoryInterface struct {
	mock.Mock
}

type MockOrderRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepositoryInterface) EXPECT() *MockOrderRepositoryInterface_Expecter {
	return &MockOrderRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: order
func (_m *MockOrderRepositoryInterface) Create(order *models.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - order *models.Order
func (_e *MockOrderRepositoryInterface_Expecter) Create(order interface{}) *MockOrderRepositoryInterface_Create_Call {
	return &MockOrderRepositoryInterface_Create_Call{Call: _e.mock.On("Create", order)}
}

func (_c *MockOrderRepositoryInterface_Create_Call) Run(run func(order *models.Order)) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Order))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Create_Call) Return(_a0 error) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepositoryInterface_Create_Call) RunAndReturn(run func(*models.Order) error) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockOrderRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrderRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockOrderRepositoryInterface_Expecter) Delete(id interface{}) *MockOrderRepositoryInterface_Delete_Call {
	return &MockOrderRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockOrderRepositoryInterface_Delete_Call) Run(run func(id uint)) *MockOrderRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Delete_Call) Return(_a0 error) *MockOrderRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepositoryInterface_Delete_Call) RunAndReturn(run func(uint) error) *MockOrderRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: limit, offset
func (_m *MockOrderRepositoryInterface) GetAll(limit int, offset int) ([]models.Order, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Order, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Order); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockOrderRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockOrderRepositoryInterface_Expecter) GetAll(limit interface{}, offset interface{}) *MockOrderRepositoryInterface_GetAll_Call {
	return &MockOrderRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll", limit, offset)}
}

func (_c *MockOrderRepositoryInterface_GetAll_Call) Run(run func(limit int, offset int)) *MockOrderRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_GetAll_Call) Return(_a0 []models.Order, _a1 error) *MockOrderRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepositoryInterface_GetAll_Call) RunAndReturn(run func(int, int) ([]models.Order, error)) *MockOrderRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockOrderRepositoryInterface) GetByID(id uint) (*models.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockOrderRepositoryInterface_Expecter) GetByID(id interface{}) *MockOrderRepositoryInterface_GetByID_Call {
	return &MockOrderRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockOrderRepositoryInterface_GetByID_Call) Run(run func(id uint)) *MockOrderRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_GetByID_Call) Return(_a0 *models.Order, _a1 error) *MockOrderRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepositoryInterface_GetByID_Call) RunAndReturn(run func(uint) (*models.Order, error)) *MockOrderRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: userID, limit, offset
func (_m *MockOrderRepositoryInterface) GetByUserID(userID uint, limit int, offset int) ([]models.Order, error) {
	ret := _m.Called(userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Order, error)); ok {
		return rf(userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Order); ok {
		r0 = rf(userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepositoryInterface_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockOrderRepositoryInterface_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - userID uint
//   - limit int
//   - offset int
func (_e *MockOrderRepositoryInterface_Expecter) GetByUserID(userID interface{}, limit interface{}, offset interface{}) *MockOrderRepositoryInterface_GetByUserID_Call {
	return &MockOrderRepositoryInterface_GetByUserID_Call{Call: _e.mock.On("GetByUserID", userID, limit, offset)}
}

func (_c *MockOrderRepositoryInterface_GetByUserID_Call) Run(run func(userID uint, limit int, offset int)) *MockOrderRepositoryInterface_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_GetByUserID_Call) Return(_a0 []models.Order, _a1 error) *MockOrderRepositoryInterface_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepositoryInterface_GetByUserID_Call) RunAndReturn(run func(uint, int, int) ([]models.Order, error)) *MockOrderRepositoryInterface_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: order
func (_m *MockOrderRepositoryInterface) Update(order *models.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - order *models.Order
func (_e *MockOrderRepositoryInterface_Expecter) Update(order interface{}) *MockOrderRepositoryInterface_Update_Call {
	return &MockOrderRepositoryInterface_Update_Call{Call: _e.mock.On("Update", order)}
}

func (_c *MockOrderRepositoryInterface_Update_Call) Run(run func(order *models.Order)) *MockOrderRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Order))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Update_Call) Return(_a0 error) *MockOrderRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepositoryInterface_Update_Call) RunAndReturn(run func(*models.Order) error) *MockOrderRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *MockOrderRepositoryInterface) UpdateStatus(id uint, status models.OrderStatus) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, models.OrderStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepositoryInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepositoryInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id uint
//   - status models.OrderStatus
func (_e *MockOrderRepositoryInterface_Expecter) UpdateStatus(id interface{}, status interface{}) *MockOrderRepositoryInterface_UpdateStatus_Call {
	return &MockOrderRepositoryInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status)}
}

func (_c *MockOrderRepositoryInterface_UpdateStatus_Call) Run(run func(id uint, status models.OrderStatus)) *MockOrderRepositoryInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(models.OrderStatus))
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_UpdateStatus_Call) Return(_a0 error) *MockOrderRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepositoryInterface_UpdateStatus_Call) RunAndReturn(run func(uint, models.OrderStatus) error) *MockOrderRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepositoryInterface creates a new instance of MockOrderRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepositoryInterface {
	mock := &MockOrderRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
