// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/JihadRinaldi/go-shop/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCartRepositoryInterface is an autogenerated mock type for the CartRepositoryInterface type
type MockCartRepositoryInterface struct {
	mock.Mock
}

type MockCartRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepositoryInterface) EXPECT() *MockCartRepositoryInterface_Expecter {
	return &MockCartRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: cart
func (_m *MockCartRepositoryInterface) Create(cart *models.Cart) error {
	ret := _m.Called(cart)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Cart) error); ok {
		r0 = rf(cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCartRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - cart *models.Cart
func (_e *MockCartRepositoryInterface_Expecter) Create(cart interface{}) *MockCartRepositoryInterface_Create_Call {
	return &MockCartRepositoryInterface_Create_Call{Call: _e.mock.On("Create", cart)}
}

func (_c *MockCartRepositoryInterface_Create_Call) Run(run func(cart *models.Cart)) *MockCartRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Cart))
	})
	return _c
}

func (_c *MockCartRepositoryInterface_Create_Call) Return(_a0 error) *MockCartRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepositoryInterface_Create_Call) RunAndReturn(run func(*models.Cart) error) *MockCartRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockCartRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCartRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockCartRepositoryInterface_Expecter) Delete(id interface{}) *MockCartRepositoryInterface_Delete_Call {
	return &MockCartRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockCartRepositoryInterface_Delete_Call) Run(run func(id uint)) *MockCartRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCartRepositoryInterface_Delete_Call) Return(_a0 error) *MockCartRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepositoryInterface_Delete_Call) RunAndReturn(run func(uint) error) *MockCartRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: userID
func (_m *MockCartRepositoryInterface) GetByUserID(userID uint) (*models.Cart, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Cart, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Cart); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepositoryInterface_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCartRepositoryInterface_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *MockCartRepositoryInterface_Expecter) GetByUserID(userID interface{}) *MockCartRepositoryInterface_GetByUserID_Call {
	return &MockCartRepositoryInterface_GetByUserID_Call{Call: _e.mock.On("GetByUserID", userID)}
}

func (_c *MockCartRepositoryInterface_GetByUserID_Call) Run(run func(userID uint)) *MockCartRepositoryInterface_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCartRepositoryInterface_GetByUserID_Call) Return(_a0 *models.Cart, _a1 error) *MockCartRepositoryInterface_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepositoryInterface_GetByUserID_Call) RunAndReturn(run func(uint) (*models.Cart, error)) *MockCartRepositoryInterface_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: cart
func (_m *MockCartRepositoryInterface) Update(cart *models.Cart) error {
	ret := _m.Called(cart)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Cart) error); ok {
		r0 = rf(cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCartRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - cart *models.Cart
func (_e *MockCartRepositoryInterface_Expecter) Update(cart interface{}) *MockCartRepositoryInterface_Update_Call {
	return &MockCartRepositoryInterface_Update_Call{Call: _e.mock.On("Update", cart)}
}

func (_c *MockCartRepositoryInterface_Update_Call) Run(run func(cart *models.Cart)) *MockCartRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Cart))
	})
	return _c
}

func (_c *MockCartRepositoryInterface_Update_Call) Return(_a0 error) *MockCartRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepositoryInterface_Update_Call) RunAndReturn(run func(*models.Cart) error) *MockCartRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartRepositoryInterface creates a new instance of MockCartRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepositoryInterface {
	mock := &MockCartRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
