// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/JihadRinaldi/go-shop/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockProductRepositoryInterface is an autogenerated mock type for the ProductRepositoryInterface type
type MockProductRepositoryInterface struct {
	mock.Mock
}

type MockProductRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepositoryInterface) EXPECT() *MockProductRepositoryInterface_Expecter {
	return &MockProductRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: product
func (_m *MockProductRepositoryInterface) Create(product *models.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockProductRepositoryInterface_Expecter) Create(product interface{}) *MockProductRepositoryInterface_Create_Call {
	return &MockProductRepositoryInterface_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *MockProductRepositoryInterface_Create_Call) Run(run func(product *models.Product)) *MockProductRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Product))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_Create_Call) Return(_a0 error) *MockProductRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepositoryInterface_Create_Call) RunAndReturn(run func(*models.Product) error) *MockProductRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockProductRepositoryInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockProductRepositoryInterface_Expecter) Delete(id interface{}) *MockProductRepositoryInterface_Delete_Call {
	return &MockProductRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockProductRepositoryInterface_Delete_Call) Run(run func(id uint)) *MockProductRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_Delete_Call) Return(_a0 error) *MockProductRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepositoryInterface_Delete_Call) RunAndReturn(run func(uint) error) *MockProductRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: limit, offset
func (_m *MockProductRepositoryInterface) GetAll(limit int, offset int) ([]models.Product, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Product, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Product); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProductRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockProductRepositoryInterface_Expecter) GetAll(limit interface{}, offset interface{}) *MockProductRepositoryInterface_GetAll_Call {
	return &MockProductRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll", limit, offset)}
}

func (_c *MockProductRepositoryInterface_GetAll_Call) Run(run func(limit int, offset int)) *MockProductRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_GetAll_Call) Return(_a0 []models.Product, _a1 error) *MockProductRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepositoryInterface_GetAll_Call) RunAndReturn(run func(int, int) ([]models.Product, error)) *MockProductRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCategoryID provides a mock function with given fields: categoryID, limit, offset
func (_m *MockProductRepositoryInterface) GetByCategoryID(categoryID uint, limit int, offset int) ([]models.Product, error) {
	ret := _m.Called(categoryID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategoryID")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]models.Product, error)); ok {
		return rf(categoryID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []models.Product); ok {
		r0 = rf(categoryID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(categoryID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepositoryInterface_GetByCategoryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCategoryID'
type MockProductRepositoryInterface_GetByCategoryID_Call struct {
	*mock.Call
}

// GetByCategoryID is a helper method to define mock.On call
//   - categoryID uint
//   - limit int
//   - offset int
func (_e *MockProductRepositoryInterface_Expecter) GetByCategoryID(categoryID interface{}, limit interface{}, offset interface{}) *MockProductRepositoryInterface_GetByCategoryID_Call {
	return &MockProductRepositoryInterface_GetByCategoryID_Call{Call: _e.mock.On("GetByCategoryID", categoryID, limit, offset)}
}

func (_c *MockProductRepositoryInterface_GetByCategoryID_Call) Run(run func(categoryID uint, limit int, offset int)) *MockProductRepositoryInterface_GetByCategoryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_GetByCategoryID_Call) Return(_a0 []models.Product, _a1 error) *MockProductRepositoryInterface_GetByCategoryID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepositoryInterface_GetByCategoryID_Call) RunAndReturn(run func(uint, int, int) ([]models.Product, error)) *MockProductRepositoryInterface_GetByCategoryID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockProductRepositoryInterface) GetByID(id uint) (*models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *MockProductRepositoryInterface_Expecter) GetByID(id interface{}) *MockProductRepositoryInterface_GetByID_Call {
	return &MockProductRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockProductRepositoryInterface_GetByID_Call) Run(run func(id uint)) *MockProductRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_GetByID_Call) Return(_a0 *models.Product, _a1 error) *MockProductRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepositoryInterface_GetByID_Call) RunAndReturn(run func(uint) (*models.Product, error)) *MockProductRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySKU provides a mock function with given fields: sku
func (_m *MockProductRepositoryInterface) GetBySKU(sku string) (*models.Product, error) {
	ret := _m.Called(sku)

	if len(ret) == 0 {
		panic("no return value specified for GetBySKU")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Product, error)); ok {
		return rf(sku)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Product); ok {
		r0 = rf(sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepositoryInterface_GetBySKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySKU'
type MockProductRepositoryInterface_GetBySKU_Call struct {
	*mock.Call
}

// GetBySKU is a helper method to define mock.On call
//   - sku string
func (_e *MockProductRepositoryInterface_Expecter) GetBySKU(sku interface{}) *MockProductRepositoryInterface_GetBySKU_Call {
	return &MockProductRepositoryInterface_GetBySKU_Call{Call: _e.mock.On("GetBySKU", sku)}
}

func (_c *MockProductRepositoryInterface_GetBySKU_Call) Run(run func(sku string)) *MockProductRepositoryInterface_GetBySKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_GetBySKU_Call) Return(_a0 *models.Product, _a1 error) *MockProductRepositoryInterface_GetBySKU_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepositoryInterface_GetBySKU_Call) RunAndReturn(run func(string) (*models.Product, error)) *MockProductRepositoryInterface_GetBySKU_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: product
func (_m *MockProductRepositoryInterface) Update(product *models.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *models.Product
func (_e *MockProductRepositoryInterface_Expecter) Update(product interface{}) *MockProductRepositoryInterface_Update_Call {
	return &MockProductRepositoryInterface_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *MockProductRepositoryInterface_Update_Call) Run(run func(product *models.Product)) *MockProductRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Product))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_Update_Call) Return(_a0 error) *MockProductRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepositoryInterface_Update_Call) RunAndReturn(run func(*models.Product) error) *MockProductRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStock provides a mock function with given fields: id, quantity
func (_m *MockProductRepositoryInterface) UpdateStock(id uint, quantity int) error {
	ret := _m.Called(id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, int) error); ok {
		r0 = rf(id, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepositoryInterface_UpdateStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStock'
type MockProductRepositoryInterface_UpdateStock_Call struct {
	*mock.Call
}

// UpdateStock is a helper method to define mock.On call
//   - id uint
//   - quantity int
func (_e *MockProductRepositoryInterface_Expecter) UpdateStock(id interface{}, quantity interface{}) *MockProductRepositoryInterface_UpdateStock_Call {
	return &MockProductRepositoryInterface_UpdateStock_Call{Call: _e.mock.On("UpdateStock", id, quantity)}
}

func (_c *MockProductRepositoryInterface_UpdateStock_Call) Run(run func(id uint, quantity int)) *MockProductRepositoryInterface_UpdateStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepositoryInterface_UpdateStock_Call) Return(_a0 error) *MockProductRepositoryInterface_UpdateStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepositoryInterface_UpdateStock_Call) RunAndReturn(run func(uint, int) error) *MockProductRepositoryInterface_UpdateStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepositoryInterface creates a new instance of MockProductRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepositoryInterface {
	mock := &MockProductRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
