// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockUploadProvider is an autogenerated mock type for the UploadProvider type
type MockUploadProvider struct {
	mock.Mock
}

type MockUploadProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadProvider) EXPECT() *MockUploadProvider_Expecter {
	return &MockUploadProvider_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: path
func (_m *MockUploadProvider) DeleteFile(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploadProvider_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockUploadProvider_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - path string
func (_e *MockUploadProvider_Expecter) DeleteFile(path interface{}) *MockUploadProvider_DeleteFile_Call {
	return &MockUploadProvider_DeleteFile_Call{Call: _e.mock.On("DeleteFile", path)}
}

func (_c *MockUploadProvider_DeleteFile_Call) Run(run func(path string)) *MockUploadProvider_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUploadProvider_DeleteFile_Call) Return(_a0 error) *MockUploadProvider_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUploadProvider_DeleteFile_Call) RunAndReturn(run func(string) error) *MockUploadProvider_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: file, path
func (_m *MockUploadProvider) UploadFile(file *multipart.FileHeader, path string) (string, error) {
	ret := _m.Called(file, path)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) (string, error)); ok {
		return rf(file, path)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) string); ok {
		r0 = rf(file, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, string) error); ok {
		r1 = rf(file, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUploadProvider_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockUploadProvider_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - file *multipart.FileHeader
//   - path string
func (_e *MockUploadProvider_Expecter) UploadFile(file interface{}, path interface{}) *MockUploadProvider_UploadFile_Call {
	return &MockUploadProvider_UploadFile_Call{Call: _e.mock.On("UploadFile", file, path)}
}

func (_c *MockUploadProvider_UploadFile_Call) Run(run func(file *multipart.FileHeader, path string)) *MockUploadProvider_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*multipart.FileHeader), args[1].(string))
	})
	return _c
}

func (_c *MockUploadProvider_UploadFile_Call) Return(_a0 string, _a1 error) *MockUploadProvider_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUploadProvider_UploadFile_Call) RunAndReturn(run func(*multipart.FileHeader, string) (string, error)) *MockUploadProvider_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUploadProvider creates a new instance of MockUploadProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadProvider {
	mock := &MockUploadProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
